### ISSUE TITLE
Universe Items

### ISSUE THREAD

**Issue by wolfkidsounds** [wolfkidsounds/Universe-Modpack#112]
-> Universe Ore (Galacticraft)
-> Crusher = Universe Dust

Farbe - Lila Diamant (sowas in der Art)

UniverseOre
UniverseCrystal
UniverseDust

**Comment by HerrKUniverse** [comment]
![universeore](https://user-images.githubusercontent.com/79264133/109875576-eda30f80-7c70-11eb-890d-0ab71dc5a9ad.png)

**Comment by HerrKUniverse** [comment]
![universecrystal](https://user-images.githubusercontent.com/79264133/109877362-36f45e80-7c73-11eb-9d1f-85b60342ddb2.png)

**Comment by HerrKUniverse** [comment]
![universedust](https://user-images.githubusercontent.com/79264133/109878263-5cce3300-7c74-11eb-8812-e675c18ac861.png)

**Comment by wolfkidsounds** [comment]
![iron_ore](https://user-images.githubusercontent.com/32850639/109880531-52616880-7c77-11eb-9239-047ef410ecc0.png)
![glowstone_dust](https://user-images.githubusercontent.com/32850639/109880536-57beb300-7c77-11eb-80d2-2b41f876824b.png)
![diamond](https://user-images.githubusercontent.com/32850639/109880547-5b523a00-7c77-11eb-8d3c-1402886fc4c5.png)

**Comment by HerrKUniverse** [comment]
[universeitems.zip](https://github.com/wolfkidsounds/Universe-Modpack/files/6079555/universeitems.zip)

**Comment by HerrKUniverse** [comment]
[universedustv2.zip](https://github.com/wolfkidsounds/Universe-Modpack/files/6079649/universedustv2.zip)
