### ISSUE TITLE
Quests Universe Modpack

### ISSUE THREAD

**Issue by NegativImpact** [wolfkidsounds/Universe-Modpack#124]
### MC ingame Quests 
	
**Kill x Mobs**
	- Töte x Mobs
	- Töte 20 Skeletons 
	- Töte 20 Zombies
	- Töte 20 Creeper
	- Töte 20 Spiders
	- Töte 20 Enderman
	- Töte 20 Slimes
	
**Besorge x Materialien (Overworld)**
	- Besorge 2x64 Cobblestone
	- Besorge 2x64 Stone
	- Besorge 2x64 Dirt
	- Besorge 2x64 Gravel
	- Besorge 2x64 Sand
	- Besorge 2x64 Clay
	- Besorge 2x64 Wood (Oak, Birch, Dark Oak, Jungle, …)
	
**Besorge x Materialien (Nether)**
	- Besorge 2x64 Netherrack
	- Besorge 2x64 Glowstone
	- Besorge 2x64 Soul Sand
	- Besorge 2x64 Magma Blocks
	- Besorge 2x64 
	
**Handel**
	- Trade x mal mit Villagern

**Comment by wolfkidsounds** [comment]
#120

**Comment by wolfkidsounds** [comment]
#133 @NegativImpact
