### ISSUE TITLE
dont show crafting recipe, per leftclick

### ISSUE THREAD

**Issue by NegativImpact** [wolfkidsounds/Universe-Modpack#125]
<tconstruct:tooltables:2>.withTag({textureBlock: {id: "minecraft:log", Count: 1 as byte, Damage: 0 as short}})
<tconstruct:tooltables:1>.withTag({textureBlock: {id: "minecraft:planks", Count: 1 as byte, Damage: 0 as short}})
wird mit linkem mausklick nichts geöffnet

@wolfkidsounds

**Comment by NegativImpact** [comment]
ich habe direkt noch ein bug gefunden man kann den 
Stencil Table(Tinkers Construckt) sowohl mit 1x woodplanks und 1x blank Pattern als auch mit 1x Oak Wood und 1x Blank Pattern Bauen

**Comment by wolfkidsounds** [comment]
Vermutlich: https://github.com/wolfkidsounds/Universe-Modpack/blob/main/Client/scripts/mods/mod_tcon.zs
