### ISSUE TITLE
[Feature] - Mob Drops: Bending Scrolls

### ISSUE THREAD

**Issue by wolfkidsounds** [wolfkidsounds/Universe-Modpack#166]
Water Drops
> Ice Drops

Fire Drops
> Blitz, Combustion

Earth Drops
> Sand

Air Drops

**Comment by wolfkidsounds** [comment]
```/ct inventory```

**Comment by wolfkidsounds** [comment]
```<avatarmod:scroll>``` Is provided by uncle iroh to get started.

```<avatarmod:scroll:8>``` Combustion Bending Scroll
```<avatarmod:scroll:1>```Earth Bending Scroll

**Comment by stkl-tea** [comment]
erste einträge - noch nicht vollständig

[scroll drops.zip](https://github.com/wolfkidsounds/Universe-Modpack/files/6135104/scroll.drops.zip)

**Comment by stkl-tea** [comment]
alle spawneier:

[scroll drops.zip](https://github.com/wolfkidsounds/Universe-Modpack/files/6135348/scroll.drops.zip)



es fehlen:
- drachen?
- lycanites
- vllt noch welche, die die halt keine spawneier haben

**Comment by stkl-tea** [comment]
wichtig: im avatarwiki oder einem fancy tool die bisherigen scrolldrops herausfinden -> nerfen bis rausnehmen

**Comment by wolfkidsounds** [comment]
Ungefähr so bringt mir die Tabelle was (daten so roh wie möglich).
https://docs.google.com/spreadsheets/d/145t44wxL3HG9jTN5wSQaxmbGT2y6rLLPEP41mTkVcpc/edit?usp=sharing
