### ISSUE TITLE
[Feature] - Food Expansion raus?

### ISSUE THREAD

**Issue by stkl-tea** [wolfkidsounds/Universe-Modpack#204]
schaut euch mal die mod food expansion an.
finde echt cool, dass es mehr individuelle fleischarten gibt (z.b. horse, wolf, parrot...), aber die sind nicht kompatibel mit pamsHC rezepten. zudem halt mega unbalanced, und wenn wir es nach PamsHC Standard balancen, dann ist fast jedes food nutzlos.
Den Aufwand das food cool einzubinden sehe ich aktuell als überflüssig an

rausnehmen?

**Comment by wolfkidsounds** [comment]
Seh ich, bin dabei, done.
