### ISSUE TITLE
[Feature] - Soups & Co.

### ISSUE THREAD

**Issue by stkl-tea** [wolfkidsounds/Universe-Modpack#206]
Vorschlag für das Soup Balancing - hoffe, dass es in dem format bequem für dich ist ^^

https://docs.google.com/spreadsheets/d/1-1ohEe7kFbl-wTdCAqpShevAaBAZcE72jaI6aPM_onQ/edit?usp=sharing

- [x] Food (Script)
- [ ] Thirst (json)

**Comment by wolfkidsounds** [comment]
Top! :)

**Comment by wolfkidsounds** [comment]
Thirst Values: https://github.com/wolfkidsounds/Universe-Modpack/blob/4.0.3/Client/config/simpledifficulty/consumableThirst.json

**Comment by wolfkidsounds** [comment]
Food Values (null) https://github.com/wolfkidsounds/Universe-Modpack/blob/4.0.3/Client/scripts/compat/food/food_tweaker.zs

**Comment by stkl-tea** [comment]
Frage @wolfkidsounds 
ist es möglich "OreDicts" o.ä. für food-gruppierungen zu erstellen und diesen werte zuzuordnen?

der grund warum manche getränke nicht funktionierten ist wahrscheinlich, dass nur die standard-cfg der thirst mod verwendet wird und nicht unsere --> heißt auch komplett anderes balancing..
vllt komplette customization für die getränke?

**Comment by wolfkidsounds** [comment]
Für crafftweaker (also die food werte) sollte das möglich sein dort können wir sowas machen wir "for item in oreDict" und dann durch iteraten (ein neues oredict dafür zu erstellen wäre wahrscheinlich sinnvoll).

Für die "thirst values" müssen wir das eindeutig mit hand erledigen. da die json kein oredict akzeptiert.

Du musst aber bitte nochmal für mich evaluieren was "manche getränke nicht funktionieren" bedeutet?
Die gelisteten getränke haben für mich dort ehrlich gesagt kein problem gemacht..

**Comment by wolfkidsounds** [comment]
in der theorie überlege ich gerade, ob es sich grundlegend lohnt das ganze von der crafttweaker seite aus auf zu ziehen (also quasi erst das oredict dort zu erstellen und dort durch zu gehen). Denn dort existiert ja bereits eine liste an getränken, für die wir das anwenden wollen. 

Dann könnte man versuchen mit multi-cursor die json für alle gleich auf einen schlag zu schreiben..

**Comment by stkl-tea** [comment]
"Du musst aber bitte nochmal für mich evaluieren was "manche getränke nicht funktionieren" bedeutet?"

na, das hatten wir ja gemeinsam auf dem server herausgefunden, dass manche smoothies nicht trinkbar waren, wenn man durst hatte und auch keinen aufgefüllt haben, wenn man sie essen konnte, sondern nur food gegeben haben.. ich glaube der plumsmoothie war unter anderem betroffen

**Comment by wolfkidsounds** [comment]
Das war doch aber noch unter der alten version?

Das die smoothies auch "food" werte beinflussen war glaube ich noch vor #209

Das mit dem food wurde auf jeden fall hier #159 eigentlich gelöst und sollte dann in v4.0.4 richtig drin sein :)

**Comment by stkl-tea** [comment]
es war die letzte version, aber wir werden es dann sehen ^^
