### ISSUE TITLE
2x fish

### ISSUE THREAD

**Issue by stkl-tea** [wolfkidsounds/Universe-Modpack#22]
pams harvestcraft und vanilla minecraft haben den normalen fisch und salmon jeweils.
sind nicht stackbar und das crafting-rezept ist einfach nur der fisch zum umwandeln.

ist wahrscheinlich kompatibel, aber ich würde einfach einen der beiden rausnehmen

**Comment by wolfkidsounds** [comment]
```
<minecraft:fish>
<minecraft:fish:2>
<minecraft:fish:3>
<minecraft:cooked_cod>
```
