### ISSUE TITLE
[Bug] -Wieso bist du nicht auf Discord? @Wolfkidsounds :P 

### ISSUE THREAD

**Issue by HerrKUniverse** [wolfkidsounds/Universe-Modpack#225]
**Beschreibung**
*Eine klare beschreibung des bugs.*

**Bug reproduktion**
*Wie ist der bug zustande gekommen?*

**Screenshots**

**Zusätzliche Informationen**

**Comment by wolfkidsounds** [comment]
Weil ich gleich schlafe :b
