### ISSUE TITLE
[Crash] - TwitchSpawn?

### ISSUE THREAD

**Issue by HerrKUniverse** [wolfkidsounds/Universe-Modpack#233]
**Beschreibung**
TS Zusammenhang?

**Zusätzliche Informationen**
[crash-2021-03-20_20.28.49-client.txt](https://github.com/wolfkidsounds/Universe-Modpack/files/6176290/crash-2021-03-20_20.28.49-client.txt)
[crash-2021-03-20_20.28.51-client.txt](https://github.com/wolfkidsounds/Universe-Modpack/files/6176291/crash-2021-03-20_20.28.51-client.txt)
[crash-2021-03-20_20.28.53-client.txt](https://github.com/wolfkidsounds/Universe-Modpack/files/6176292/crash-2021-03-20_20.28.53-client.txt)
[crash-2021-03-20_20.28.55-client.txt](https://github.com/wolfkidsounds/Universe-Modpack/files/6176293/crash-2021-03-20_20.28.55-client.txt)
[crash-2021-03-20_20.28.39-client.txt](https://github.com/wolfkidsounds/Universe-Modpack/files/6176294/crash-2021-03-20_20.28.39-client.txt)
[crash-2021-03-20_20.28.41-client.txt](https://github.com/wolfkidsounds/Universe-Modpack/files/6176295/crash-2021-03-20_20.28.41-client.txt)
[crash-2021-03-20_20.28.43-client.txt](https://github.com/wolfkidsounds/Universe-Modpack/files/6176296/crash-2021-03-20_20.28.43-client.txt)
[crash-2021-03-20_20.28.45-client.txt](https://github.com/wolfkidsounds/Universe-Modpack/files/6176297/crash-2021-03-20_20.28.45-client.txt)
[crash-2021-03-20_20.28.47-client.txt](https://github.com/wolfkidsounds/Universe-Modpack/files/6176298/crash-2021-03-20_20.28.47-client.txt)

**Comment by wolfkidsounds** [comment]
Unrelated -> TwitchSpawn Issue
