### ISSUE TITLE
[Feature] - Balancing

### ISSUE THREAD

**Issue by HerrKUniverse** [wolfkidsounds/Universe-Modpack#241]
**Bounty Request**

- [x] Naga mob (Twilight Forest) --> hat keinen körper (nur kopf) | *fixed by blacklisting the entity culling*
- [x] Mob Drops von den eels zu op? Edit: finde ich nicht -stkl | *keine änderung*
- [x] Bendable blocks (atum) | *sand -> sandbending/earth+stone -> earthbending*
- [x] Appa Spawns | *ein weiterer (wahrscheinlich sinnloser) test...*
- [x] Bender Spawns (+drops) | *drops removed, added "potential spawn removal"*
- [x] bounty board timings  --> low quests (z.b. 40 zombie kills) dauern z.t. nur 5min nach spawn | *time increased + number of bountys and base time increased*
- [x] TinkersConstruct Smeltery (Osmium, Yellorium) | *added addon mod to make items, and materials craftable*
- [x] Water Bucket soltle 8 fresh water ergeben.
- [x] wool bounty reward nerfen (vllt so *0,66) | *weniger "unitworth" ist jetzt 3 (von vorher 5)*
- [ ] Scroll Drops testen für alle mobs | *im singleplayer droppen die mobs die scrolls*
- [x] Scrolls in dungeon loot (waren bisher noch nie drin...) | *wontfix*

 1 milk bucket (minecraft:milk_bucket) = 8x fresh milk (harvestcraft:freshmilkitem)

**Comment by wolfkidsounds** [comment]
> Edit: ok, hab jz gesehen, dass das bereits dasteht mit singeplayer scrolldrops, sorry
> 
> vllt interessant für den scroll drop fix:  bisher hat auf dem server kein mob eine bending scroll gedroppt, als rolli das aber im singeplayer getestet hat, hat ihm der erste test mit ~50 mobs ca 5 scrolls gegeben
> --> ist das vllt serverseitig nicht ganz eingebunden?

Ah interessant. Danke dir, das erklärt eventuell die ganze Sache mehr. - Also kannst du auf dem Server mit den selben mobs den selben Test noch mal durchführen? Vielleicht auch Creative fix ne Mobfarm testen oder so? - Das wäre sehr hilfreich.
