### ISSUE TITLE
[Feature] - beetrootseeds nicht craftbar

### ISSUE THREAD

**Issue by stkl-tea** [wolfkidsounds/Universe-Modpack#242]
aus beetroots lassen sich keine beetrootseeds craften

**Comment by stkl-tea** [comment]
ne, die vanilla beetroots, wobei ich mir nicht sicher bin ob pamHC die überschreibt als eigenes item o.ä.

**Comment by wolfkidsounds** [comment]
> ne, die vanilla beetroots, wobei ich mir nicht sicher bin ob pamHC die überschreibt als eigenes item o.ä.

Pam sollte an den beets gar nichts ändern. Es sollte glaube ich nicht mal ein beetroot seed item von pam geben. - Aber ich kann es wie gesagt gern hinzufügen :) (barley und wheat sollte man glaube auch nicht zu seeds craften können).

**Comment by wolfkidsounds** [comment]
So, habs mir angeschaut aus "minecraft:beetroot" kannst du auch in vanilla keine seeds machen (die droppen von grass).

---

Aus der "harvestcraft:beet" kannst du einen seed craften, kein problem.

---

Frage: Wozu das rezept für die Seeds?
