### ISSUE TITLE
Bitte Nausea (und Blindness) Effekt(e) wieder stärker machen und mit schwanken

### ISSUE THREAD

**Issue by HerrKUniverse** [wolfkidsounds/Universe-Modpack#246]
Das ist Teil meiner TwitchSpawn Troll Sache und das möchte ich gern wieder drin haben.
Bei Blindness bin ich mir unsicher, ob es raus ist, sollte jedenfalls wie bei Tintenfischen sein.

- [x] Nausea
- [ ] Blindness (quark) -> config change in twitchspawn?

**Comment by wolfkidsounds** [comment]
@HerrKUniverse : Die Blindness von den tintenfischen ist ein gesonderter effekt von der mod "quark". -> Das ist kein vanilla feature!
