### ISSUE TITLE
pamsHC fish trap recipe

### ISSUE THREAD

**Issue by stkl-tea** [wolfkidsounds/Universe-Modpack#25]
lässt sich nur mit der vanilla oak chest craften --> alle kisten, vanilla wie "mod-holz"

**Comment by wolfkidsounds** [comment]
Biomes O Plenty Chest benötigen OreDict -> ```<ore:chestWood>```

**Comment by wolfkidsounds** [comment]
```<harvestcraft:watertrap>```
