### ISSUE TITLE
[Feature] - 20 neue bountys

### ISSUE THREAD

**Issue by stkl-tea** [wolfkidsounds/Universe-Modpack#250]
mache ich die tage, vorschläge könnt ihr gerne hier posten

**Comment by wolfkidsounds** [comment]
Weitere "seltenere" log sorten.
Zeug aus dem Nether/End
Zeug von Planeten/Twilight/Atum
Mob Drops (Slime, Rotten Flesh, Blazew Rods)


Skeleton Warrior/Fallen Knight


Firebender, Airbender lol


Tinker Parts/Items

**Comment by stkl-tea** [comment]
bereits integriert
