### ISSUE TITLE
[Feature] - force serverrestart

### ISSUE THREAD

**Issue by stkl-tea** [wolfkidsounds/Universe-Modpack#254]
force serverrestart 1x täglich ohne playercheck --> fühl ich mehr, um damit rechnen zu können, dass "bugs sich von selbst fixen"

- [x] forced restart 02.30uhr

**Comment by wolfkidsounds** [comment]
>  force serverrestart 1x täglich ohne playercheck --> fühl ich mehr, um damit rechnen zu können, dass "bugs sich von selbst fixen"

Geht klar, Bau ich ein :)
