### ISSUE TITLE
[Bug] - Anzeige & Items inkorrekt (SimpleStorageNetwork)

### ISSUE THREAD

**Issue by NegativImpact** [wolfkidsounds/Universe-Modpack#265]
**Beschreibung**
im Simple storage Network werden items in Doppelter anzahl angezeigt.
*Eine klare beschreibung des bugs.*

**Bug reproduktion**
bei allen items die ich in das Storage system Lege
*Wie ist der bug zustande gekommen?*
war schon immer da °
**Screenshots**
![2021-04-06_13 10 46](https://user-images.githubusercontent.com/71758466/113702345-ad083d00-96d9-11eb-8319-ea4f5e981d65.png)
![2021-04-06_13 10 50](https://user-images.githubusercontent.com/71758466/113702352-ae396a00-96d9-11eb-9ea3-d0f61899dcd5.png)

**Zusätzliche Informationen**
wie in den bildern gezeigt habe ich im Storage 22 Flint aber wenn ich alle raus nehme habe ich nur 11 also die hälfte

---

- [x] Drawer Controller (allein)
- [x] Drawer (allein)
- [x] Chest/Iron Chest
- [x] Drawer + Drawer Controller?

**Comment by NegativImpact** [comment]
ich habe auch gerade raus gefunden das dass nur bei den Storage Drawern passiert und nicht wenn man Kisten an das System Anschließst
@wolfkidsounds

**Comment by wolfkidsounds** [comment]
Teste mal ob die storage drawer "locked" sind bzw. Ob welche in Kisten liegen/welche in Drawern. (Also ob du die zwei mal heraus nehmen kannst)

**Comment by wolfkidsounds** [comment]
Sind die Storage Drawer über den Drawer Controller oder einzeln (oder sogar doppelt) angeschlossen?

**Comment by wolfkidsounds** [comment]
Das ist kein Bug, sondern ein "Feature" -> Also eine Fehlnutzung. Der Drawer Controller ist ein eigenes Inventarsystem und der zeigt die items bereits an (wenn drawer angeschlossen sind). Schließt man die Drawer seperat zusätzlich an, werden die Items auch "doppelt" im system angezeigt.
