### ISSUE TITLE
[Bug] - Suppen exorbitant OP

### ISSUE THREAD

**Issue by stkl-tea** [wolfkidsounds/Universe-Modpack#272]
ist vllt iwo ein multiplikator vor den werten?

weil aus irgendeinem grund können z.B. die <harvestcraft:blazingsoupitem> und die <harvestcraft:lambbarleysoupitem> 60x bzw 30x die saturation auffüllen

![2021-04-10_13 59 20](https://user-images.githubusercontent.com/79314316/114269064-f8398d00-9a04-11eb-9fd3-895dc2051c76.png)

**Comment by wolfkidsounds** [comment]
related #206 das ist eine sache, die du schon die ganze zeit machen wolltest :D

**Comment by stkl-tea** [comment]
naja nein.. ich wollte die thirst werte eintragen, nicht die hungerwerte quadrieren

**Comment by wolfkidsounds** [comment]
Ju, war die suppe in der liste zwecks der thirst werte? Denn wenn ich den hunger lösche, ist die suppe absolut useless.

**Comment by stkl-tea** [comment]
ne, in der aktuellen nicht. der hunger sollte denke ich auch nicht komplett gelöscht werden, sondern nur generft (auch wenn es eigentlich keine rolle spielt.. man hat nur eine saturationbar und über diese hinaus passiert nichts mehr)
ich weiß nur nicht inwiefern dieses feature noch sinnvoll ist

**Comment by wolfkidsounds** [comment]
hmn, naja dann warte ich noch auf die thirst werte, sonst lohnt es sich nicht die food werte mehrfach neu an zu passen. :)

**Comment by wolfkidsounds** [comment]
Als referenz, hier sind die soup-werte die ich bisher von dir bekommen habe: https://github.com/wolfkidsounds/Universe-Modpack/blob/main/Client/scripts/compat/food/tweaks/soup_tweaks.zs

**Comment by stkl-tea** [comment]
nein, nicht auf alle
