### ISSUE TITLE
[Feature] - feature für den lieben stefan? :)

### ISSUE THREAD

**Issue by stkl-tea** [wolfkidsounds/Universe-Modpack#274]
<chisel:marble2:7> in <extraplanets:decorative_blocks> umcraftbar machen? :D

ich mag den chisel marble block nicht, aber ich will für nen deko block auch nicht über tier 3 rockets bauen müssen 😅

**Comment by wolfkidsounds** [comment]
@HerrKUniverse  was sagst du dazu`? :)

**Comment by stkl-tea** [comment]
![5294f693-0fe6-4174-a81d-8b6166d438de](https://user-images.githubusercontent.com/79314316/114275016-36dd4080-9a21-11eb-9944-e90ab93f5b92.jpg)
![0c2c1137-9ddc-42be-be54-794ecef9c1e8](https://user-images.githubusercontent.com/79314316/114275017-380e6d80-9a21-11eb-98fc-5d24afbb8697.jpg)
