### ISSUE TITLE
[Bug] - damage timer fix

### ISSUE THREAD

**Issue by stkl-tea** [wolfkidsounds/Universe-Modpack#276]
<biomesoplenty:flower_0:15> hat keinen damage timer (burning blossom im nether)

**Comment by wolfkidsounds** [comment]
Ist keine entity -> brauche hier den "damageType" (zB. thorns, inLava, hypothermia ...)

**Comment by stkl-tea** [comment]
die macht firedamage
hilft dir das was?

**Comment by wolfkidsounds** [comment]
habs anders gelöst, firedamage ist bereits auf der liste. Denke den typ da genau raus zu bekommen ist schwere als die immunity allgemein für spieler weg zu lassen.
