### ISSUE TITLE
[Feature] - Skeleton Horses spawnrate reduzieren

### ISSUE THREAD

**Issue by stkl-tea** [wolfkidsounds/Universe-Modpack#280]
wenn in die skeleton horses ein blitz einschlägt, dann spawnen ca 3 weitere + skeletons mit bogen als reiter auf ihnen und deren spawnrate ist übertrieben hoch

das ist der mob, aber das horse alleine macht ja nichts --> es gibt das event mit dem blitz
"minecraft:skeleton_horse"

**Comment by wolfkidsounds** [comment]
vanilla feature -> https://minecraft.fandom.com/wiki/Skeleton_Horse
