### ISSUE TITLE
avatar-armory, metal ore spawnrate vierteln

### ISSUE THREAD

**Issue by stkl-tea** [wolfkidsounds/Universe-Modpack#34]
- armors auf dialevel lassen
- metal ore chance dafür weit runterstellen (darf ruhig mehr als normale dias sein)

**Comment by wolfkidsounds** [comment]
Dafür benötigen wir COFH World (o.ä.) https://www.curseforge.com/minecraft/mc-mods/cofh-world

Da die config das in der Avatar Armory mod nicht her gibt :(
