### ISSUE TITLE
Configure: Custom Loading Screen

### ISSUE THREAD

**Issue by wolfkidsounds** [wolfkidsounds/Universe-Modpack#41]

**Comment by HerrKUniverse** [comment]
![loadingscreen](https://user-images.githubusercontent.com/79264133/108610513-6a62fd80-73d6-11eb-99fa-c7689b31f77f.png)

**Comment by wolfkidsounds** [comment]
@HerrKUniverse vergiss dich selbst nicht 👯

**Comment by HerrKUniverse** [comment]
@wolfkidsounds ich glaube ich stehe im Titel und sonst hustlet ihr da technisch viel mehr rein als ich, somit finde ich das eig cool so ^^ Ich hab bisschen rumprobiert und diese Anleitung probiert:

"Temporary instructions, I'll update these when it's been tested to work properly:

1. Download https://www.curseforge.com/minecraft/mc-mods/better-loading-screen/files/3208087
2. In `config/customloadingscreen.cfg` Change `S:screen_config` to `S:screen_config=sample/slideshow`
3. Create a folder `config/customloadingscreen/`
4. Add your slideshow images in `config/customloadingscreen/` named `slideshow_1.png`, `slideshow_2.png`, `slideshow_3.png`, etc"

Aber es hat beim Laden nicht den Screen angezeigt und gesagt, dass es "Error: couldn't find the config file 'sample/slideshow'"
