### ISSUE TITLE
lit campfire with firebending

### ISSUE THREAD

**Issue by stkl-tea** [wolfkidsounds/Universe-Modpack#57]
tough as nails: campfire auch mit firebending anzünden?

**Comment by wolfkidsounds** [comment]
Eigentlich sollten die ToughAsNails sachen nicht mehr im JEI auftauchen und auch kein Crafting Rezept mehr besitzen: 
https://github.com/wolfkidsounds/Universe-Modpack/blob/3.9.2/Client/scripts/mods/mod_taughasnails.zs

**Comment by stkl-tea** [comment]
naja, es gibt noch viel mehr tough as nails items, die in der datei nicht angeführt werden ^^
aber ja, die können im prinzip auch alle raus

**Comment by wolfkidsounds** [comment]
Ich habe jetzt alle generved.
-> https://github.com/wolfkidsounds/Universe-Modpack/commit/18b7cace29a0f40740d71614f928caa58ddf6db0#
