### ISSUE TITLE
Mystical Agriculture

### ISSUE THREAD

**Issue by wolfkidsounds** [wolfkidsounds/Universe-Modpack#9]
Lower Drop Rates / Ban Plant essence
(balancing)

**Comment by HerrKUniverse** [comment]
Dia-Pflanze bannen

**Comment by wolfkidsounds** [comment]
possile fix using: https://github.com/wolfkidsounds/Universe-Modpack/commit/007d912c4fa350e72ee4aa349825503cac6a31cd

**Comment by wolfkidsounds** [comment]
fixed in #40
