### ISSUE TITLE
Configure Custom Main Menu

### ISSUE THREAD

**Issue by wolfkidsounds** [wolfkidsounds/Universe-Modpack#95]

**Comment by HerrKUniverse** [comment]
[mainmenu.zip](https://github.com/wolfkidsounds/Universe-Modpack/files/6079967/mainmenu.zip)
Update!
mainmenu json für config/custommainmenu
mainmenu ordner unter ressources

**Comment by wolfkidsounds** [comment]
[mainmenu.zip](https://github.com/wolfkidsounds/Universe-Modpack/files/6083482/mainmenu.zip)
